README.md
Add the links for the Hex package & docs. Also trim some of the contents, since it's covered in the docs
=> Add docs & package to README

.travis.yml
Run the code formatter check as the first part of our test build.
=> Check that code is formatted before running tests

README.md, lib/new_relic/tracer.ex
This PR adds some basic instrumentation documentation to the top level README
=> Add basic instrumentation docs to the Readme

lib/new_relic/harvest/collector/metric_data.ex
This adds a simple metric that is incremented for every harvest cycle.
@mattbaker
=> Add a metric for all harvests

README.md
Created the contribution section and the brief text about signing the CLA.
=> Added section for CLA

lib/new_relic/instrumented/httpoison.ex, test/instrumented_test.exs
=> Add `request/5` to HTTPoison instrumenter

lib/new_relic/sampler/beam.ex
Adds a few more stats about memory usage
=> Add binary and code memory usage to beam sampler

lib/new_relic/transaction/reporter.ex
When generating Span events, we only send those that have `sampled: true`. This logic is in place for standard spans, but wasn't in place for the span we auto-generate to represent the Cowboy process handling a request.
=> Properly sample cowboy process span

lib/new_relic/harvest/collector/protocol.ex
For better debugging, let's log the method we called on the collector along with the status code
=> Log the collector method along with status code

lib/new_relic/distributed_trace.ex, lib/new_relic/harvest/collector/span_event/harvester.ex, lib/new_relic/span/event.ex, lib/new_relic/tracer/macro.ex, lib/new_relic/tracer/report.ex, lib/new_relic/transaction/reporter.ex, lib/new_relic/transaction/trace.ex, lib/new_relic/util.ex, test/span_event_test.exs, test/transaction_trace_test.exs
This PR improves:
* Function tracers - will be nested inside eachother within the process they are called inside
* Process tracking - processes will be nested mirroring the structure of how they were spawned
These improvements apply to:
* Transaction Traces
* Distributed Traces & Spans
sidekick/ @mattbaker !
closes #18
=> Improved function and process nesting

lib/new_relic/transaction/reporter.ex, test/transaction_test.exs
Simple PR that counts the number of processes involved in a Transaction
closes #75
=> Track process spawn count

lib/new_relic/sampler/beam.ex
Useful along side scheduler count
=> Track cpu count too

lib/new_relic/error/reporter.ex, lib/new_relic/transaction/complete.ex, lib/new_relic/util/error.ex
This PR improves the messaging for `EXIT` type error reports..
=> Format EXIT error reporting better

lib/new_relic/transaction/complete.ex
We should only report process spans if the transaction itself has been sampled.
=> Omit process spans when they aren't sampled

README.md, lib/new_relic.ex, lib/new_relic/transaction.ex
Hi,
It would be nice to find documentation about "Ignoring transactions" in README and Hexdocs.
I hope this MR will be useful for other people as well.
BR, Maxim
=> Add docs about "Ignore transactions"

lib/new_relic/harvest/collector/harvest_cycle.ex
It was possible that a harvester could leak & not get shutdown if an edge case hit & the harvest couldn't be sent within the timeout
=> Make sure the harvester shuts down even upon timeout

lib/new_relic.ex, lib/new_relic/application.ex, lib/new_relic/enabled_supervisor.ex, lib/new_relic/harvest/collector/agent_run.ex, lib/new_relic/harvest/collector/custom_event/harvester.ex, lib/new_relic/harvest/collector/data_supervisor.ex, lib/new_relic/harvest/collector/error_trace/harvester.ex, lib/new_relic/harvest/collector/harvest_cycle.ex, lib/new_relic/harvest/collector/harvester_supervisor.ex, lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/harvest/collector/span_event/harvester.ex, lib/new_relic/harvest/collector/transaction_error_event/harvester.ex, lib/new_relic/harvest/collector/transaction_event/harvester.ex, lib/new_relic/harvest/collector/transaction_trace/harvester.ex, lib/new_relic/transaction.ex, lib/new_relic/util/priority_queue.ex, test/custom_event_test.exs, test/error_trace_test.exs, test/metric_harvester_test.exs, test/span_event_test.exs, test/transaction_error_event_test.exs, test/transaction_event_test.exs, test/transaction_trace_test.exs
A few fixes to clear up Dialyzer warnings. Including one that actually caught a bug that we had missed
=> Dialyzer fixes

lib/new_relic/telemetry/ecto/metadata.ex
An update to a few items in Ecto result struct handing
* Sometimes the `command` is a list
* Mysql update parsing
=> Ecto result handling

lib/new_relic/config.ex, lib/new_relic/harvest/collector/agent_run.ex, lib/new_relic/harvest/collector/connect.ex, lib/new_relic/harvest/collector/custom_event/harvester.ex, lib/new_relic/harvest/collector/error_trace/harvester.ex, lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/harvest/collector/protocol.ex, lib/new_relic/harvest/collector/span_event/harvester.ex, lib/new_relic/harvest/collector/transaction_error_event/harvester.ex, lib/new_relic/harvest/collector/transaction_event/harvester.ex, lib/new_relic/harvest/collector/transaction_trace/harvester.ex, test/integration/integration_test.exs
This PR upgrades to "protocol 17" which enables a feature that sends event data to New Relic much faster.
=> Protocol 17

lib/new_relic/distributed_trace/new_relic_context.ex, lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex, lib/new_relic/telemetry/ecto/handler.ex, lib/new_relic/telemetry/ecto/metadata.ex, lib/new_relic/telemetry/ecto/supervisor.ex
=> Mark modules private

lib/new_relic/config.ex
=> Fix incorrect config env var

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/transaction/complete.ex
This PR includes a few adjustments to metrics to adapt to the fact that we're sending scoped metrics now
=> Scoped metric naming

CHANGELOG.md, examples/apps/ecto_example/test/ecto_example_test.exs, examples/apps/w3c_trace_context_validation/.gitignore, examples/apps/w3c_trace_context_validation/config/config.exs, examples/config/config.exs, lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/telemetry/ecto/handler.ex, lib/new_relic/transaction/complete.ex
This PR reports Database metrics as scoped transaction metrics!
=> Scoped database metrics

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/transaction/complete.ex
Tweak to the metrics sent in to make sure the Breakdown overview chart renders as expected
=> Scope metric tweak

lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex, test/wc3_trace_context_test.exs
This PR handles cases when another New Relic agent sends a bad w3c `tracestate` formatted header. This happens because some agents were released that serialize the priority field as scientific notation when it's a very small value.
Also sets us up to handle "future" versions that might have more segments.
=> Handle bad NR tracestate

README.md
Adds a bit more of information to `readme.md` to give better context for newcomers on non-web transactions
If anything is out of standard or could be improved, please let me know
=> Add other transactions to readme.md

examples/apps/ecto_example/test/ecto_example_test.exs, lib/new_relic/harvest/collector/metric_data.ex
This PR adds a few more Datastore metrics so that the Overview charts are properly displayed
=> Report Datastore allWeb metrics

lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/metric/metric.ex, test/metric_test.exs
This PR contains a simple memory usage optimization for the Metric harvester which will improve memory usage for very high throughput apps
=> Optimize metric harvester

.travis.yml, lib/new_relic/aggregate/reporter.ex, lib/new_relic/aggregate/supervisor.ex, lib/new_relic/always_on_supervisor.ex, lib/new_relic/application.ex, lib/new_relic/distributed_trace/backoff_sampler.ex, lib/new_relic/distributed_trace/supervisor.ex, lib/new_relic/distributed_trace/tracker.ex, lib/new_relic/enabled_supervisor.ex, lib/new_relic/enabled_supervisor_manager.ex, lib/new_relic/error/supervisor.ex, lib/new_relic/graceful_shutdown.ex, lib/new_relic/harvest/collector/agent_run.ex, lib/new_relic/harvest/collector/data_supervisor.ex, lib/new_relic/harvest/collector/harvester_store.ex, lib/new_relic/harvest/collector/supervisor.ex, lib/new_relic/harvest/supervisor.ex, lib/new_relic/logger.ex, lib/new_relic/sampler/agent.ex, lib/new_relic/sampler/beam.ex, lib/new_relic/sampler/ets.ex, lib/new_relic/sampler/process.ex, lib/new_relic/sampler/supervisor.ex, lib/new_relic/sampler/top_process.ex, lib/new_relic/telemetry/ecto/supervisor.ex, lib/new_relic/telemetry/redix.ex, lib/new_relic/telemetry_supervisor.ex, lib/new_relic/transaction/monitor.ex, lib/new_relic/transaction/reporter.ex, lib/new_relic/transaction/supervisor.ex
This PR adopts the new(ish) Supervisor specs to clear out warnings in Elixir 1.10
=> Elixir 1.10

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/transaction/complete.ex, test/metric_transaction_test.exs, test/other_transaction_test.exs
This PR adds a few more Errors metrics specific to the Transaction Type
=> Report error metric for transaction type

.github/workflows/elixir.yml
* Test major versions instead of a matrix
* Cache `examples/deps` and `examples/_build` for integration tests
=> Test major versions

lib/new_relic.ex
=> Quick docs improvement

lib/new_relic/harvest/collector/custom_event/harvester.ex, lib/new_relic/harvest/collector/span_event/harvester.ex, lib/new_relic/util.ex
Similar to #267 , this PR correctly processes Span event attributes for invalid values
fixes #266
=> Properly process span event attributes

lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/metric/metric.ex, lib/new_relic/metric/metric_data.ex, lib/new_relic/transaction/complete.ex, test/metric_test.exs, test/metric_transaction_test.exs, test/sampler_test.exs
This PR leverages the erlang `counter` module top optimize cpu and memory usage by metric collection.
=> Optimize metric collection with counters

lib/new_relic/sampler/beam.ex
This ensures that we return nil, not 0, if cpu_sup is disabled, and prevents endless log warnings about cpu_sup not being enabled.
=> Only get CPU utilization if os_mon's cpu_sup is enabled

lib/new_relic/init.ex, test/init_test.exs
Boolean config option wasn't getting handled properly
Fixes #293
=> Properly handle harvest_enabled config

lib/new_relic/error/reporter.ex, test/transaction_error_event_test.exs
This PR handles an edge case with error stacktrace parsing
Fixes #299
=> Handle formatting exit edge case

lib/new_relic/application.ex, lib/new_relic/enabled_supervisor.ex, lib/new_relic/sampler/beam.ex, lib/new_relic/signal_handler.ex
This PR returns the behavior of the agent before #287 with a workaround for the issue here: https://bugs.erlang.org/projects/ERL/issues/ERL-1392
Fixes #298
=> Work around CPU utili issues

.github/workflows/elixir.yml
Wait for mysql in GH Action so that we know it's ready when the tests run
=> Wait for mysql in GH Action

README.md, lib/new_relic/harvest/telemetry_sdk/config.ex, test/telemetry_sdk/config_test.exs
This PR fixes the Telemetry API URLs for the EU region
Continued from #324
=> Fix Telemetry API URLS for EU

.github/workflows/elixir.yml
Improve the cache & compile behavior
=> Optimize Github Actions

.github/workflows/elixir.yml
This PR splits unit and integration tests into their own jobs so they run in parallel
=> Github action - split Unit and Integration tests

.github/workflows/elixir.yml
=> GH action - use default for integration working dir

lib/new_relic/transaction/erlang_trace.ex, test/sidecar_test.exs
This PR extends our process tracer to include `proc_lib:start_link` so that, for example: a GenServer started & linked from inside a Transaction is included in that Transaction
=> Include start_link in Transaction tracer

.github/workflows/elixir.yml
Run CI on Elixir 1.12 - OTP 24
=> Run CI on Elixir 1.12 - OTP 24

examples/apps/ecto_example/test/ecto_example_test.exs, lib/new_relic/telemetry/ecto/metadata.ex
This PR aims to implement the feature request mentioned in #353.
=> Correct categorization of simpler database queries

README.md
Mention the new option in the README so it's discoverable
=> Mention httpc config options in README

lib/new_relic/sampler/process.ex
Protect against race conditions in Process Sampler math. In case a process dies while we are sampling it.
Closes #367
=> Safer math in Process sampler

lib/new_relic/config.ex, lib/new_relic/harvest/collector/connect.ex, lib/new_relic/init.ex, lib/new_relic/transaction/complete.ex, test/collector_protocol_test.exs, test/transaction_test.exs
Supports setting "host display name"
https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/configuration/add-rename-remove-hosts/#display_name
Closes #450
=> Support host display name

lib/new_relic/telemetry/phoenix_live_view.ex
Turns out the `meta.uri` field can be nil in some cases.
Fixes #509
=> Handle when LiveView meta.uri is nil
