README.md, config/test.exs, lib/new_relic/aggregate/reporter.ex, lib/new_relic/config.ex, lib/new_relic/harvest/collector/agent_run.ex, lib/new_relic/harvest/collector/protocol.ex, lib/new_relic/harvest/collector/transaction_trace/harvester.ex, lib/new_relic/init.ex, lib/new_relic/sampler/reporter.ex, lib/new_relic/transaction/reporter.ex, mix.exs, test/collector_stub_test.exs, test/config_test.exs, test/custom_event_test.exs, test/error_trace_test.exs, test/integration/agent_run_test.exs, test/integration/collector_test.exs, test/metric_harvester_test.exs, test/span_event_test.exs, test/tracer_test.exs, test/transaction_error_event_test.exs, test/transaction_event_test.exs, test/transaction_trace_test.exs
The name `new_relic` is already taken, so we already call the Hex package `new_relic_agent`. This PR switches the name of the application as well, so we don't get confused.
=> Call the app `new_relic_agent`

test/backoff_sampler_test.exs, test/test_helper.exs
The timing is different in Travis, so this PR is increasing the async wait that we'll do to allow instrumentation events to get collected
=> Increase the async delay for tests

test/tracer_test.exs
Make sure test ordering doesn't cause conflicts with expected results
=> Fix a test ordering collision

lib/new_relic/harvest/collector/protocol.ex, lib/new_relic/util.ex, mix.exs
This PR uses `HTTPoison` for internal agent http requests, which also means it's now a non-optional dep.
@mattbaker
=> Use HTTPoison for agent http requests

lib/new_relic/instrumented/httpoison.ex, test/instrumented_test.exs
Adds a note about matching against the return `HTTPoison` struct
sidekick/ @mattbaker 
closes/ #26
=> Note that original HTTPoison structs are returned

lib/new_relic/harvest/collector/custom_event/harvester.ex, lib/new_relic/harvest/collector/data_supervisor.ex, lib/new_relic/harvest/collector/error_trace/harvester.ex, lib/new_relic/harvest/collector/harvest_cycle.ex, lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/harvest/collector/span_event/harvester.ex, lib/new_relic/harvest/collector/transaction_error_event/harvester.ex, lib/new_relic/harvest/collector/transaction_event/harvester.ex, lib/new_relic/harvest/collector/transaction_trace/harvester.ex, test/custom_event_test.exs, test/error_trace_test.exs, test/metric_harvester_test.exs, test/span_event_test.exs, test/transaction_error_event_test.exs, test/transaction_event_test.exs, test/transaction_trace_test.exs
This PR extends the time that a harvester Task is willing to wait for the `send_harvest` action. The action is essentially doing an HTTPoison request, which has it's own built-in timeout values of `8000` for connecting and `5000` for receiving a response.
The Task isn't blocking anything so this won't impact anything else in the agent.
=> Extend the timeout on harvester send_harvest

lib/new_relic.ex
This improves the docs around Transaction naming
closes #32
=> Clarify Transaction naming convention

lib/new_relic/application.ex, lib/new_relic/config.ex, lib/new_relic/transaction/reporter.ex, test/test_helper.exs, test/transaction_error_event_test.exs, test/transaction_test.exs
For environments where error reporting is not desired, the `error_reporting_enabled` config can be
set to false.
@binaryseed do you have any suggestions on the best way to test the dynamic application.ex setup? I was thinking of an integration style test in transaction_error_event_test.exs, but it would involve tearing down the entire application supervisor and restarting it. That could be done with `async: false` and would be safe. edit: Turns out that async: false is the default, so it's simply a matter of wanting to go that route.
=> Optionally disable error reporting

lib/new_relic/transaction/reporter.ex, lib/new_relic/util.ex, test/transaction_test.exs, test/util_test.exs
This PR will flatten any attribute value that is a map so that it's component parts all show up as their own attributes.
In favor of #39
=> Flatten attributes that are maps

lib/new_relic/sampler/beam.ex, lib/new_relic/sampler/process.ex, test/sampler_test.exs
This PR adds a few more statistics to the `Beam` sampler, including scheduler utilization
Also changed variable names since I got confused. `previous` is better than `last` since it's chronological order we are comparing.
=> Extend Beam sampler stats

.travis.yml, lib/new_relic/sampler/beam.ex
In https://github.com/newrelic/elixir_agent/pull/38 we used some new stats from OTP 21. But for OTP 20 compat we need to protect against those calls...
To protect against this we're now running tests in OTP 20 and 21
=> Test against OTP 20 and 21

lib/new_relic/sampler/beam.ex, lib/new_relic/sampler/ets.ex, lib/new_relic/sampler/process.ex, lib/new_relic/sampler/reporter.ex, lib/new_relic/sampler/supervisor.ex, lib/new_relic/sampler/top_process.ex, lib/new_relic/util/priority_queue.ex, test/sampler_test.exs
This PR adds a new sampler that will detect the top processes (according to memory & message queue length) and report on them
Also
* A few tweaks to the other process sampler to make it safer
* Randomize the start of each of the samplers so they all don't run at once
=> Detect and sample the top processes

lib/new_relic/harvest/collector/metric_data.ex
Simplify and fix an edge case around metric name joining.
Instead of #43
=> Fix metric name join

lib/new_relic/transaction.ex, lib/new_relic/transaction/reporter.ex
Splitting this functionality in order to use the failure marking separate from completing the transaction.
=> Split the functionality of stop(error)

lib/new_relic/transaction/plug.ex, lib/new_relic/transaction/reporter.ex
This PR extends Transaction naming storage so that we can have more flexibility.
1) Custom name if set
2) Framework name if set (for phoenix, etc)
3) Fallback to plug name
=> Add more flexibility for Transaction naming

lib/new_relic/transaction/plug.ex, lib/new_relic/transaction/reporter.ex
Always set the `plug_name` upon Transaction stop, instead of in the Plug. This will make it easier to stop the transaction in other adapters.
=> Set plug_name upon stop

lib/new_relic/harvest/collector/agent_run.ex
Update the agent to report as `elixir` instead of `sdk`
**WIP**: the New Relic ingest pipeline is being updated to support this
=> Report as elixir

lib/new_relic/error/error_handler.ex, lib/new_relic/error/error_logger_handler.ex, lib/new_relic/error/logger_handler.ex, lib/new_relic/error/reporter.ex, lib/new_relic/error/supervisor.ex, test/error_trace_test.exs
This improves our ability to connect an Error and the Transaction it was part of since the OTP 21 `:logger` executes the callback in the originating process, instead of receiving it as an async `gen_event`!
=> Leverage OTP 21 `:logger` when we can

lib/new_relic/transaction/plug.ex
This adds a few stats to each transaction for `memory_kb` and `reductions` of the main Transaction process (not including any async processes that contributed to the request)
=> Record a few stats after each transaction

lib/new_relic/config.ex, lib/new_relic/logger.ex, test/config_test.exs, test/logger_test.exs
Traditionally, New Relic agents push our log messages to a specific file, primarily for easy access to them if someone needs support. This PR adds another setting which enables them to be sent to the standard Elixir `Logger` if someone wants that.
Opt-in by:
```elixir
config :new_relic_agent, log: "Logger"
```
closes #64
=> Allow setting the logger to use Logger

lib/new_relic/config.ex, lib/new_relic/harvest/collector/agent_run.ex, test/config_test.exs
An agent is able to report to as many as 3 different applications. This PR enables that behavior. App names are split by the `;` char.
=> Handle multiple app names properly

lib/new_relic/config.ex
This handles the case when an app name isn't yet specified
=> Handle when no app name specified

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/tracer/report.ex, test/metric_tracer_test.exs
This PR un-hard-codes the datastore adapter name in prep for `ecto` instrumentation
=> More flexible datastore metric names

lib/new_relic/error/reporter.ex
This PR cleans up the shape of some kinds of exceptions that currently are wrapped up in a few layers. This directly extracts the relevant exception & stacktrace
=> Add another parsing function for exception shapes

lib/new_relic/util.ex, test/util_test.exs
This PR adds a special condition that reports the `DYNO` env var in Heroku as the `hostname`.
closes #77
=> Detect heroku hostnames

lib/new_relic/distributed_trace/context.ex, lib/new_relic/distributed_trace/plug.ex, lib/new_relic/error/reporter.ex, lib/new_relic/harvest/collector/custom_event/harvester.ex, lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/tracer/report.ex, lib/new_relic/transaction/reporter.ex, test/custom_event_test.exs, test/distributed_trace_test.exs, test/error_trace_test.exs, test/integration/collector_test.exs, test/span_event_test.exs, test/transaction_error_event_test.exs, test/transaction_event_test.exs
Elixir 1.8.0 soft deprecates some things, eg: `deprecated time unit`
=> Clear deprecation warnings in 1.8.0

lib/new_relic/distributed_trace/context.ex, lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/harvest/collector/metric_data.ex, test/distributed_trace_test.exs
This fixes up our error handling for bad Distributed Trace header payloads
* Log at `debug`
* Send a supportability metric
=> Proper error handling for bad DT payloads

lib/new_relic/util.ex, lib/new_relic/util/vendor.ex, test/util_test.exs
Closes #74 by protecting against exceptions when attempting to see if AWS metadata is accessible.
Most of this PR is a re-shuffle of the vendor specific functions
=> Safer AWS metadata query

lib/new_relic.ex, lib/new_relic/transaction.ex, lib/new_relic/transaction/reporter.ex, test/transaction_test.exs
Add a function that enables the user to mark the current transaction to be ignored. The agent will stop tracking information about it and won't report any information about it.
```elixir
NewRelic.ignore_transaction()
```
closes #52
=> Enable ignoring a transaction

lib/new_relic/distributed_trace.ex, lib/new_relic/tracer/macro.ex, test/span_event_test.exs
This prevents span attributes from leaking into other spans when there are multiple nested spans traced in a single process.
=> Reset the span attributes after reporting them

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/transaction/complete.ex, lib/new_relic/transaction/event.ex, test/transaction_test.exs
This PR calculates and sends metrics for the "total time" of a transaction, which includes the total time spent in all concurrent processes involved in a transaction.
=> Send total time metrics

lib/new_relic.ex, lib/new_relic/application.ex, lib/new_relic/graceful_shutdown.ex, lib/new_relic/harvest/collector/harvest_cycle.ex, lib/new_relic/harvest/supervisor.ex, test/integration/agent_run_test.exs
This PR will wire up the supervision tree so that we attempt to send the data in the harvesters before we fully shut down.
=> Attempt a graceful shutdown when the app exits

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/tracer/report.ex, lib/new_relic/transaction/complete.ex, lib/new_relic/transaction/reporter.ex, test/metric_transaction_test.exs, test/other_transaction_test.exs, test/transaction_test.exs
We want to track some metrics for reporting later, since they depend on information from the transaction they occur in.
=> Report external metrics based on transaction type

lib/new_relic/transaction/complete.ex, test/transaction_event_test.exs
Fix a bug that put the wrong name attribute on Transaction events (web vs. other)
=> Fix name prefix for transaction event

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/transaction/complete.ex
In rare conditions a required attribute might not get captured, and this PR updates the agent to handle that case, log the error & move on..
closes #101
=> Handle edge case when required attr isn't captured

lib/new_relic/harvest/collector/custom_event/harvester.ex, lib/new_relic/harvest/collector/error_trace/harvester.ex, lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/harvest/collector/span_event/harvester.ex, lib/new_relic/harvest/collector/transaction_error_event/harvester.ex, lib/new_relic/harvest/collector/transaction_event/harvester.ex, lib/new_relic/harvest/collector/transaction_trace/harvester.ex
Drop the log level for the output from harvesters from `info` to `debug`
closes #104
=> Lower log level for harvesters

lib/new_relic/util/priority_queue.ex, test/priority_queue_test.exs
Fixes #108 by using [`:erlang.unique_integer/0`](http://erlang.org/doc/man/erlang.html#unique_integer-0`) to ensure that we're generating a unique key for the `gb_tree`.
=> Fix `Erlang error: {:key_exists, ...}`

lib/new_relic/util/error.ex, test/error_test.exs
=> More formatting improvements for exit errors

lib/new_relic/transaction/monitor.ex, test/transaction_error_event_test.exs, test/transaction_test.exs
Discovered a race condition where, when an `async_nolink` process is started within a transaction, if it finishes after the transaction has completed, the transaction it is linked to no longer exists so the process's results will not be reported.
This PR removes the linking of an `async_nolink` process to a transaction so that it will consistently be reported to the agent. Note: when using erlang 20, the logging is async and the race condition still exists.
=> Fix: race condition when tracing async_nolink processes

lib/new_relic/transaction/monitor.ex, test/transaction_error_event_test.exs, test/transaction_test.exs
Reverts newrelic/elixir_agent#118
Turns out we didn't think far enough ahead. It's a little more complex since there's multiple use cases for  actually considering the work in an `async_nolink` as part of the Transaction.
We're going to think about this and see how we can solve this problem better!
=> Revert "Fix: race condition when tracing async_nolink processes"

lib/new_relic/transaction/complete.ex
In some race conditions, the HTTP `status` attribute might not get reported. This PR handles that case.
=> Protect against missing http status

lib/new_relic/config.ex, lib/new_relic/error/error_logger_handler.ex, lib/new_relic/error/logger_handler.ex, lib/new_relic/error/reporter.ex, lib/new_relic/graceful_shutdown.ex, lib/new_relic/harvest/collector/connect.ex, lib/new_relic/util/vendor.ex
This PR ignores a category of error report that is generated by Plug + Cowboy for 400 level exceptions which crash the Cowboy process yet are caught by Plug.
Also fixes a few modules to be excluded from docs
=> Ignore extraneous Plug errors

lib/new_relic/util/error.ex
This PR improves the formatting of ErlangError by unwrapping them and displaying the underlying error better
=> Improve formatting of ErlangError

lib/new_relic/tracer/report.ex, lib/new_relic/transaction/complete.ex, test/transaction_trace_test.exs
This PR is intended to protect against excessive memory usage in cases where a very large term is passed through a `@trace`d function.
This is done by `inspect`ing the term at the point of instrumentation before we store it inside a TransactionTrace or Span. `Inspect` has mechanisms for short-circuiting it's work, and we leverage those.
I tested this in our GraphQL service, which contains `Absinthe` structs that are known to be gigantic. The resulting data was 20x smaller, and avoided a full memory copy of the struct. Yay!
=> Protect against huge arguments blowing out memory

lib/new_relic/harvest/collector/connect.ex, lib/new_relic/util.ex, lib/new_relic/util/vendor.ex, test/integration/agent_run_test.exs, test/util_test.exs
This PR adds the needed wiring to detect that the agent is inside a kubernetes cluster. Some kubernetes setup is also required.
There's a little refactoring in the surrounding areas to make this possible.
NR docs: 
* https://docs.newrelic.com/docs/integrations/kubernetes-integration/link-your-applications/link-your-applications-kubernetes
closes #139 
sidekick @mattbaker
=> K8s support

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/transaction/complete.ex, lib/new_relic/transaction/event.ex, lib/new_relic/transaction/plug.ex, lib/new_relic/transaction/request_queue_time.ex, test/metric_transaction_test.exs, test/new_relic/transaction/request_queue_time_test.exs, test/transaction_test.exs
Okay, this is for #141. It's the biggest PR I've done here, so it probably has a good bit that could be changed.
Goals:
* Track `queueDuration` as seconds (fractional to the microsecond) on web transactions
* The queue start time is interpreted from one of `"x-request-start", "x-queue-start", "x-middleware-start"`, as per the Ruby implementation
* The queue start time can be microseconds, milliseconds, or seconds (fractions supported)
* Clock skew, start time in the future, is interpreted as "now"
* WebFrontend/QueueTime metric is dispatched with completed requests
The Ruby implementation served as inspiration for deriving queue start, but I didn't handle some cases like having a compound header, or multiple headers with different values.
I haven't tried it in practice, yet.
=> Sb8244 request queue

lib/new_relic.ex
Adds an additional note since 2 segments are needed for the APM Transactions UI to work properly
closes #147
cc @sb8244
=> Add extra note about segments

README.md, lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/tracer.ex, lib/new_relic/tracer/report.ex, lib/new_relic/util.ex, test/metric_tracer_test.exs
This PR enables naming External metrics after the host of the `HTTP` request being made instead of the `Module.function`.
For this to happen, you must instrument the outgoing HTTP request function with `@trace` like normal, as well as setting the needed span attributes:
```elixir
@trace {:request, category: :external}
def request(method, url, headers) do
NewRelic.set_span(:http, url: url, method: method, component: "HttpClient")
HttpClient.request(method, url, headers)
end
```
This PR pulls in #130 with some changes to match the set of metrics we need to report. Thanks @CaiqueMitsuoka
closes #129
=> Enable naming External metrics with HTTP request host

lib/new_relic/always_on_supervisor.ex, lib/new_relic/application.ex, lib/new_relic/enabled_supervisor.ex, lib/new_relic/harvest/collector/supervisor.ex, test/test_helper.exs
This PR prevents some processes from starting if the agent is not `enabled?`
closes #144
=> Control processes started when disabled

.travis.yml, README.md, lib/new_relic/init.ex, mix.exs
This PR will cause the agent to fail fast if the application is pre-OTP 21. We already rely on some features in OTP 21 and the agent will fail with unhelpful errors.
I considered other options like not starting the application supervision tree but that may cause it's own set of problems if there are calls to `NewRelic` functions for instrumentation, etc. Open to thoughts on this...
closes #150 
closes #138 
=> Raise if not running OTP 21

lib/new_relic/harvest/collector/agent_run.ex, lib/new_relic/harvest/collector/protocol.ex, lib/new_relic/util/http.ex, test/integration/collector_test.exs
This PR:
* Directly passes the error reason so that `AgentRun` doesn't know about the error type. This should be a no-op change
* Adds a `connect_timeout` to HTTP requests since the default is `:infinity`
=> Directly handle error reason

lib/new_relic.ex, lib/new_relic/util.ex, test/util_test.exs
When adding custom attributes to an event, there are limits that get applied in the data processing pipeline.
This PR pre-emptively truncates large nested data structures so that we don't blow out the attribute count & that we can track a bit of meta-info (map size, list length).
Open to tweaking the truncation number (it's 10 now)
=> Truncate large custom attribute counts

lib/new_relic/always_on_supervisor.ex, lib/new_relic/harvest/supervisor.ex
Put this GenServer in the `AlwaysOn` supervision tree to ensure the ETS table is available always. This cleans up some edge cases when shutting down if the agent was never turned on (ie: tests)
=> Move HarvesterStore to always on

.travis.yml, lib/new_relic/transaction/complete.ex, test/metric_transaction_test.exs, test/transaction_test.exs
To help enable sending TT segments that don't track the start and end time directly and thus pass in time attributes differently...
=> Minor refactor in TT complete

test/distributed_trace_test.exs, test/support/test_helper.ex
Lots of async things happen in the tests, this little tweak helps avoid a flaky test failure
=> Cleanup test that is flaky sometimes

lib/new_relic/tracer/report.ex
Dialyzer tells us these function heads will never be called! Bye!
=> Remove redundant function heads

lib/new_relic/telemetry/ecto/handler.ex
Some config options are optional, so defaulting according to new relic metric naming conventions
closes #171
=> Safely access optional ecto config

examples/apps/ecto_example/lib/ecto_example/migration.ex, examples/apps/ecto_example/lib/ecto_example/router.ex, examples/apps/ecto_example/test/ecto_example_test.exs, lib/new_relic/telemetry/ecto/metadata.ex
When there is an error (e.g., a failed constraint) Ecto returns a result with an error tuple, instead of ok. This would raise as an unsupported Ecto adapter. Instead, we should ignore those results (at least until we can do something with them).
=> Handle Postgrex error results

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/tracer/report.ex, lib/new_relic/transaction/complete.ex, test/metric_transaction_test.exs, test/other_transaction_test.exs, test/support/test_helper.ex
This PR adds reporting of "scoped" external metrics. This provides external metrics broken down by transaction name.
@tpitale
=> Scoped external metrics

lib/new_relic/distributed_trace/new_relic_context.ex, test/distributed_trace_test.exs
This fixes a bug that was caused by defaulting the sampling flag in cases when it shouldn't have had a value. Later on the agent will make a sampling decision of its own, and this is what we want to happen...
closes #176
=> Fix sampling decision default

.travis.yml, lib/new_relic/tracer/macro.ex
When upgrading one of my apps to Elixir 1.10 I ran into a function clause error
```
:defp
:name_of_function
[{:http_result, [line: 347], nil}, {:\\, [line: 347], [{:ok_code_or_codes, [line: 347], nil}, 200]}]
[]
[]
Attempted function clauses (showing 3 out of 3):
def __on_definition__(_env, _access, _name, _args, _guards, nil)
def __on_definition__(env, _access, name, _args, _guards, [do: _, rescue: _])
def __on_definition__(%{module: module}, access, name, args, guards, [do: body])
```
The test suite already had a failure when running under 1.10, so I just added the missing function head. I also added the Elixir version under the travis config.
Let me know if there's anything else I should do before getting this merged. Thanks!
=> elixir 1.10.2 fixes

lib/new_relic/application.ex, lib/new_relic/enabled_supervisor.ex, lib/new_relic/enabled_supervisor_manager.ex, lib/new_relic/harvest/collector/agent_run.ex, test/integration/integration_test.exs, test/test_helper.exs
Alternative to #184 that uses a `DynamicSupervisor` to let us complete the boot cycle after we know we've connected inside `AgentRun`
This removes the blocking call that we previously relied on to ensure boot order.
fixes https://github.com/newrelic/elixir_agent/pull/184
@mattbaker @tpitale
=> Boot block prevention take 2

lib/new_relic/config.ex, lib/new_relic/tracer.ex, lib/new_relic/tracer/report.ex, test/transaction_trace_test.exs
This PR adds a feature toggle around function argument tracing so that it can be disabled if sensitive information is in the arguments. Also if lots of tracing is happening, this reduces memory footprint
closes #157
=> Enable ignoring arguments in traces

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/tracer/macro.ex, lib/new_relic/tracer/report.ex, lib/new_relic/transaction/complete.ex, test/metric_tracer_test.exs, test/metric_transaction_test.exs
This PR
* Reports "scoped" function trace metrics
* Calculates "exclusive time" for those function traces
* Improves the data in the Transaction Trace for viewing scoped metrics
=> Report scoped function trace metrics

lib/new_relic/distributed_trace.ex, lib/new_relic/distributed_trace/new_relic_context.ex, lib/new_relic/distributed_trace/w3c_trace_context.ex, test/distributed_trace_test.exs
Fix a bug if we get a bad payload value for the NR distributed trace header
=> Handle bug with bad NR DT payload

examples/apps/ecto_example/lib/ecto_example/count.ex, examples/apps/ecto_example/lib/ecto_example/router.ex, lib/new_relic/telemetry/ecto/metadata.ex
When using `Ecto.stream`, we get telemetry events with cursor results that we need to handle
=> Handle Ecto stream telemetry events

lib/new_relic.ex, lib/new_relic/transaction.ex, lib/new_relic/transaction/monitor.ex, lib/new_relic/transaction/plug.ex, lib/new_relic/transaction/reporter.ex
This PR provides an API to stop an Other transaction. This is needed if a single Process executes more than one transaction, which is the case for some batch processing frameworks like Broadway.
* `NewRelic.stop_transaction()` must be called when the work is complete before starting another transaction in the same Process
This must be used in conjunction with `NewRelic.start_transaction/2`. It is _not_ to be used inside "Web" transactions.
fixes #180
=> Provide an API to stop an Other transaction

lib/new_relic/telemetry/ecto.ex
Note that the agent needs to be started before the Ecto app so it can detect the Repos
closes #199
=> Note dependency order with ecto

lib/new_relic/util/vendor.ex, test/util_test.exs
If the agent detects that the app is running inside a container the container ID is added to the utilization map as:
%{docker: %{id: "<CONTAINER_ID>"}}
The conatainer ID is taken from the file "/proc/self/cgroup". It's taken from the first cgroup in the file that meets the following requirements: 
- The definition must contain 3 parts separated by a colon.
- It must specify the cpu subsystem.
- The contianer ID is the last item in the cgroup path and it should be a 64-digit hex string. 
Fixes https://github.com/newrelic/elixir_agent/issues/204
=> Add docker id to the utilization vendors

examples/apps/ecto_example/mix.exs, mix.exs
This PR simply makes the agent depend on:
* `plug` directly
* `plug_cowboy` optionally
The agent does use Plug functions for header manipulation, but doesn't directly use any cowboy functions, we simply need to enforce a requirement on Cowboy version 2 if it is there
Functionally, this shouldn't change anything since the app itself should be including `plug` / `plug_cowboy` if it uses them... 
This simply reduces the number of deps the agent will pull in on it's own
=> Make plug_cowboy dep optional

lib/new_relic/transaction/reporter.ex, lib/new_relic/util.ex, test/transaction_test.exs
This PR handles user-supplied attributes of types that aren't normally JSON serializable.
A set of types we can easily `inspect` or `to_string` to get a meaningful value. Another set we reject since we can't serialize it to JSON in a meaningful way - like tuples / functions.
=> Coercion of custom attributes

lib/new_relic/util/http.ex, mix.exs, mix.lock, test/ssl_test.exs, test/util_test.exs
OTP 21+ (which we require) has a built-in SSL hostname verification function that we can use instead of relying on a dependency...
Described in the Erlang Elixir Foundation Security guide:
* https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/ssl
=> Use built-in SSL hostname check

lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/sampler/agent.ex, lib/new_relic/sampler/supervisor.ex, lib/new_relic/transaction/complete.ex, lib/new_relic/transaction/reporter.ex, lib/new_relic/util/attr_store.ex, test/attr_store_test.exs, test/distributed_trace_test.exs, test/metric_transaction_test.exs, test/sampler_test.exs, test/tracer_test.exs, test/transaction_event_test.exs, test/transaction_test.exs, test/transaction_trace_test.exs
This PR splits the Transaction backing store into 2 ETS tables, one for tracking processes that are part of a Transaction, and one for collecting the attributes for Transactions.
The goal of this is to reduce contention in cases of the app being overloaded.
=> Split ets tables for tracking and collecting

lib/new_relic/distributed_trace.ex, lib/new_relic/distributed_trace/new_relic_context.ex, lib/new_relic/logger.ex, lib/new_relic/util.ex, test/distributed_trace_test.exs, test/transaction_test.exs
The New Relic Browser agent now supports DT, and there are some incorrect assumptions in the agent about which attributes will be present in the payload.
This PR fixes those assumptions to match what actually happens - there's no "transaction" (`tx`) attribute.
A few more fixes are included:
* Properly encode two DT payload values as strings
* Match the latest expected DT behavior & always send the Span ID
* Match expected nil attribute value behavior - don't coerce nil values, instead exclude them
=> Connect Browser Distributed Traces

lib/new_relic/error/reporter.ex, lib/new_relic/transaction/reporter.ex, test/other_transaction_test.exs
This fix ensures that "Other" transactions properly account for an error by using the main error reporting function. Web transactions via Plug already did this.
=> Transaction error reporting fix

.travis.yml, README.md, examples/apps/instrumented_task/.formatter.exs, examples/apps/instrumented_task/.gitignore, examples/apps/instrumented_task/README.md, examples/apps/instrumented_task/lib/example_task.ex, examples/apps/instrumented_task/mix.exs, lib/new_relic/harvest/collector/agent_run.ex, lib/new_relic/harvest/collector/harvest_cycle.ex, lib/new_relic/instrumented/mix_task.ex, test/other_transaction_test.exs
This PR adds a macro for easy instrumentation of a `Mix.Task`
It will:
* Start the agent
* Ensure it's booted
* Start a Transaction
* Stop the Transaction
* Send the data and stop the agent
Also makes sure there aren't any errors when the agent shuts down w/o having connected to New Relic's servers.
=> Mix.Task instrumentation

lib/new_relic/tracer/macro.ex, test/tracer_test.exs
Fixes a compile error when tracing a function that assigns a value to an ignored argument, like:
```elixir
def function(true = _ignored), do: true
```
fixes #227
=> Handle traced function with ignored and assigned arg

lib/new_relic/tracer/macro.ex, test/tracer_macro_test.exs, test/tracer_test.exs
Fixes a tracer compilation issue when an argument is a matched struct with `enforced_keys`
fixes #229
=> Fix tracer bug with struct literal and enforced_keys

lib/new_relic/tracer/macro.ex, test/tracer_test.exs
When rewriting traced functions, we need to differentiate between special forms (`__MODULE__`) and ignored variables (`_ignored`)
Fixes #234
=> Fix bug when tracing special form argument

lib/new_relic/tracer/macro.ex, test/tracer_test.exs
The previous fix for tracers on functions with pattern matched structs needs to be extended for structs that match on `%__MODULE__{}` as the struct name vs the literal module name.
Fixes #236
=> Fix tracer compile bug with struct referenced via module

lib/new_relic/error/reporter.ex, lib/new_relic/transaction.ex, lib/new_relic/transaction/monitor.ex, lib/new_relic/transaction/reporter.ex, test/transaction_error_event_test.exs, test/transaction_test.exs
In the 1.18 release (https://github.com/newrelic/elixir_agent/pull/220) there was a regression in the Transaction `error` attribute handling which started putting the attribute on Transactions in cases that previously didn't have the attribute.
This PR fixes that by splitting the handling of an "error" happening and the whole Transaction experiencing "failure". Only in the "failure" state should the Transaction get the `error = true` attribute
=> Fix regression with Transaction error attribute

lib/new_relic/tracer/macro.ex, test/tracer_test.exs
There can be a number of function level clauses (`rescue`, `after`). If there are any besides just a `do`, we can't `@trace` the function. This PR updates the logic that catches & warns for that situation...
closes #254
=> Handle any version of function level clauses in tracer

README.md
Just a small documentation update for clarity. As written the NewRelic headers are not passed to the `HttpClient`.
=> headers needs to be reassigned to include the NewRelic.distributed_trace_headers

lib/new_relic/tracer/macro.ex
I think New Relic agent keeps unnecessary data in the process dictionary.
It causes memory bloat on the process that lives for a long time.
This PR changed to remove the data after submitting tracing information.
I have developed an Elixir application with [Broadway](https://github.com/dashbitco/broadway).
The application pulls data from a message bus and processes them.
I noticed the Erlang VM memory usage had been increasing over a few days.
Then, I attached the application and investigated the memory usage of the processes.
This snippets shows the TOP 64 processes sort by memory usage.
```elixir
mems =
for pid <- :erlang.processes() do
{:erlang.process_info(pid, :memory), pid}
end
tops = mems |> Enum.sort() |> Enum.reverse() |> Enum.take(64)
res = tops |> Enum.map(fn {_, pid} ->
{_, …
```
=> Fix memory bloat in process dictionary

lib/new_relic/harvest/collector/custom_event/harvester.ex, test/aggregate_test.exs, test/custom_event_test.exs, test/sampler_test.exs, test/tracer_test.exs, test/transaction_test.exs
This PR runs Custom Events through the same attribute processing step as built-in events so that bad values don't cause errors.
Fixes #266
=> Properly process custom event attributes

lib/new_relic/harvest/collector/custom_event/harvester.ex, lib/new_relic/harvest/collector/error_trace/harvester.ex, lib/new_relic/harvest/collector/metric_data.ex, lib/new_relic/harvest/collector/span_event/harvester.ex, lib/new_relic/harvest/collector/transaction_error_event/harvester.ex, lib/new_relic/harvest/collector/transaction_event/harvester.ex, test/custom_event_test.exs
This PR extends the logs to include how many events were "seen", not just sent. Also sends some supportability metrics with the same information.
=> Log harvest seen

lib/new_relic/transaction/complete.ex, test/transaction_test.exs
This PR removes the reporting of "`ElixirAggregate`" custom events that specifically track `Transactions`.
This behavior is a left-over from a very early version of the agent, and is redundant. The equivalent data is reported directly as `Transaction` events.
=> Stop reporting aggregate events for Transaction

lib/new_relic/tracer/report.ex, test/tracer_test.exs, test/transaction_test.exs
This PR removes the reporting of "ElixirAggregate" custom events that specifically track Function Tracers.
This behavior is a left-over from a very early version of the agent, and is redundant. The equivalent data is reported directly as Metrics, which can be queried with NRQL:
```
FROM Metric
SELECT count(newrelic.timeslice.value) 
WHERE appName = 'MyApp'
TIMESERIES FACET service SINCE 1 hour AGO 
WITH METRIC_FORMAT 'External/{service}/all'
```
```
FROM Metric
SELECT count(newrelic.timeslice.value) 
WHERE appName = 'MyApp'
TIMESERIES FACET function SINCE 1 hour AGO 
WITH METRIC_FORMAT 'Function/{function}'
```
=> Stop reporting aggregate for FunctionTrace

lib/new_relic/sampler/agent.ex, lib/new_relic/sampler/beam.ex, lib/new_relic/sampler/ets.ex, lib/new_relic/sampler/process.ex, lib/new_relic/sampler/reporter.ex, lib/new_relic/sampler/top_process.ex
This PR tweaks the Samplers such that they are spread out across the full sample cycle.
Before "faster event harvest", all harvesters reported on a 60 second cycle. With "faster event harvest" they report at 5 second intervals. That means that the current behavior clumps all the `Sample` events together in the same harvest and then skips 2 harvests.
This situation can be improved by spreading the samplers evenly over the `sample_cycle`.
=> Spread samplers across full sample cycle

lib/new_relic/tracer/macro.ex, test/tracer_test.exs
Don't warn about using `@trace` on function with `rescue`, `else`, etc. if there is no `@trace` attribute set.
Running `mix test` before:
after:
=> Avoid @trace warning when unnecessary

lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex, lib/new_relic/metric/metric_data.ex, test/transaction_trace_test.exs, test/wc3_trace_context_test.exs
If a `tracestate` reaches us with a missing sampled flag but it does have a priority, we need to make sure we generate a new sampling decision.
=> Handle missing tracestate sampled value

lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex
This PR makes sure the agent can handle encoding unexpected `nil` in the Distributed Tracing sampled flag.
Fixes #281
=> Handle encoding unexpected nil

lib/new_relic.ex, lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/metric/metric_data.ex, test/metric_test.exs
This PR adds an API function for reporting custom metrics to New Relic.
```elixir
NewRelic.report_custom_metric("My/Metric", 123.4)
```
Which can then be [queried in NRDB](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/query-apm-metric-timeslice-data-nrql):
```
FROM Metric
SELECT average(newrelic.timeslice.value)
WHERE appName = 'MyApp' AND metricTimesliceName = 'Custom/My/Metric'
TIMESERIES SINCE 1 hour ago
```
=> Report custom metrics

lib/new_relic/sampler/beam.ex
There seems to be some kind of bug / race when shutting down & checking `:cpu_sup.util`, so this PR makes that check safe.
Fixes #286
=> Safely get cpu util

lib/new_relic/config.ex, lib/new_relic/init.ex, lib/new_relic/transaction/plug.ex, test/config_test.exs, test/metric_transaction_test.exs, test/transaction_test.exs, test/transaction_trace_test.exs
This PR enables configuration of the request queuing metric & attribute collection.
Alongside, it moves feature state storage to `persistent_term`
=> Configure request queuing metric collection

lib/new_relic/util/error.ex
Handle the case when a lone string winds up in the stacktrace
=> Handle string in stacktrace

lib/new_relic/util/http.ex
The agent does it's best to ensure that bad data can't make it into a payload sent to New Relic, but since we accept attributes and input from outside sources, we aren't catching 100%. This PR ensures that when we can't encode the payload, we handle and log instead of raise.
closes #266
=> Don't blow when bad data gets in

lib/new_relic.ex, test/other_transaction_test.exs
I added a macro to support "Other" transaction.
I miss often calling `NewRelic.stop_transaction/0` function.
This helper macro will avoid it.
=> Add NewRelic.transaction macro

lib/new_relic/signal_handler.ex, lib/new_relic/util.ex, test/collector_protocol_test.exs
This PR updates the environment reported up to New Relic:
* Add runtime `ERTS Version`
* Update `OTP Version` to the runtime OTP version (`Elixir build` includes the OTP version used during Elixir compilation)
=> Add more versions to environment values

lib/new_relic.ex, lib/new_relic/config.ex, lib/new_relic/distributed_trace.ex, lib/new_relic/harvest/collector/protocol.ex, lib/new_relic/harvest/collector/span_event/harvester.ex, lib/new_relic/harvest/harvest_cycle.ex, lib/new_relic/harvest/supervisor.ex, lib/new_relic/harvest/telemetry_sdk/api.ex, lib/new_relic/harvest/telemetry_sdk/config.ex, lib/new_relic/harvest/telemetry_sdk/logs/harvester.ex, lib/new_relic/harvest/telemetry_sdk/span/harvester.ex, lib/new_relic/harvest/telemetry_sdk/spans/harvester.ex, lib/new_relic/harvest/telemetry_sdk/supervisor.ex, lib/new_relic/init.ex, lib/new_relic/metric/metric_data.ex, lib/new_relic/span/event.ex, lib/new_relic/span/reporter.ex, lib/new_relic/tracer/macro.ex, lib/new_relic/transaction/complete.ex, test/collector_protocol_test.exs, test/infinite_tracing_test.exs, test/init_test.exs, test/integration/integration_test.exs, test/logs_in_context_test.exs, test/span_event_test.exs, test/telemetry_sdk/config_test.exs, test/telemetry_sdk/span_harvester_test.exs
This PR adds support for Infinite Tracing! This features significantly improves the Distributed Tracing experience by collecting 100% of Spans and sending them to a dedicated Trace Observer endpoint for processing.
https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/infinite-tracing/introduction-infinite-tracing
This feature is only on when the agent is configured to point to a Trace Observer with either
* `NEW_RELIC_INFINITE_TRACING_TRACE_OBSERVER_HOST= your_trace_observer_host` or
* `config :new_relic_agent, infinite_tracing_trace_observer_host: your_trace_observer_host`
=> Infinite tracing

lib/new_relic/tracer/report.ex, test/infinite_tracing_test.exs, test/transaction_trace_test.exs
This PR tweaks the attribute names added in #309 to avoid confusion with the `trace.id` attribute which identifies the overall Distributed Trace, not the individual tracer function.
=> Quick tweak of tracer attributes

lib/new_relic/transaction/complete.ex, test/infinite_tracing_test.exs
This PR makes sure the `automatic_attributes` are put on the `Span` event generated for a Transaction when Infinite Tracing is on.
=> Add automatic attributes to the Spansaction

lib/new_relic/tracer/macro.ex, lib/new_relic/tracer/report.ex, test/infinite_tracing_test.exs, test/span_event_test.exs, test/transaction_trace_test.exs
This PR adds an attribute to Span events that tracks the number of `reductions` done during the function call. This is meaningful since the `reductions` track the "work" done on the CPU whereas `duration` tracks wall clock time (which could be spent waiting)
Also included is a minor tweak to the inspect options used to render the function args
=> Track tracer reductions

lib/new_relic.ex, lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/metric/metric_data.ex, test/metric_test.exs
So that you can have a simple counter which can then be graphed. It
defaults to incrementing by 1 unless a value is passed in. Which enables
it to be incremented by any number.
This follows a similar method signature to the [Ruby][1] and [Node.js][2]
agents.
[1]: https://docs.newrelic.com/docs/agents/ruby-agent/api-guides/ruby-custom-metrics#increment_metric
[2]: https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api#increment_metric
=> Add ability to increment custom metrics

lib/new_relic/util/http.ex
When bad data has wound up in the payload, we need to safely log it
=> Inspect failed output going to log

.github/workflows/elixir.yml, lib/new_relic/span/event.ex, lib/new_relic/transaction/trace.ex
This PR adresses additional code paths that process attributes to ensure they exclude invalid values.
=> Coerce TT segment attributes

lib/new_relic/harvest/telemetry_sdk/config.ex, test/telemetry_sdk/config_test.exs
The region extracted from licence keys such as `eu01xx________` is `eu01`, which works for the tracing, but not for logging in context. The [logging API docs](https://docs.newrelic.com/docs/logs/log-management/log-api/introduction-log-api/#endpoint) require `https://log-api.eu.newrelic.com/log/v1`, but currently, the URL ends up as `https://log-api.eu01.newrelic.com/log/v1` which fails to report any data.
=> Fix logs in context region URL

lib/new_relic/logs_in_context.ex, test/logs_in_context_test.exs
=> Handle IO lists so that the new relic logs show strings, rather than lists in the UI

lib/new_relic/logs_in_context.ex, test/logs_in_context_test.exs
Previously only whole-process metadata added via `Logger.metadata()` would be picked up. Now calls like `Logger.error("FOO", baz: :qux)` will send `"metadata.bax": "qux"` to New Relic, whereas previously that would be missing.
=> Include metadata which has been added with a specific log message

lib/new_relic/logs_in_context.ex, test/logs_in_context_test.exs
This PR adds support for per-log message metadata.
Continued from #328
=> Support per-log message metadata

.github/workflows/elixir.yml, examples/apps/instrumented_task/lib/example_task.ex, examples/apps/instrumented_task/lib/instrumented_task.ex, examples/apps/instrumented_task/lib/uninstrumented_task.ex, examples/apps/test_support/mix.exs, lib/new_relic/harvest/harvester_store.ex
This PR ensures that even if the `new_relic_agent` application wasn't started (ex: in a mix task), calls to instrumentation functions will not fail.
=> Ensure instrumentation calls don't fail if app not started

lib/new_relic/telemetry/ecto/metadata.ex
This PR fixes an edge case with Ecto table name escape char parsing while generalizing it a bit further
=> Fix table name escaping parsing

examples/apps/ecto_example/test/ecto_example_test.exs, lib/new_relic/telemetry/ecto/handler.ex, lib/new_relic/telemetry/ecto/metadata.ex
Fix an edge case parsing the table name out of queries like `SELECT my_lock()`. Also includes a bit more code cleanup in this area.
=> Fix parsing of other SELECTs

lib/new_relic/util.ex
When a process is spawned on a remote node, the transaction monitor tries to get its name by calling `Process.info`, which always raises badarg when the Pid given to it is non-local. This results in the transaction monitor terminating, when it's probably more desirable to just continue without a name.
=> Handle exception when inspecting remote process

lib/new_relic/harvest/collector/metric/harvester.ex, lib/new_relic/telemetry/ecto/handler.ex, lib/new_relic/telemetry/plug.ex, lib/new_relic/telemetry/redix.ex, lib/new_relic/tracer/macro.ex, lib/new_relic/tracer/report.ex, lib/new_relic/transaction/complete.ex, test/other_transaction_test.exs
This PR increases the "resolution" of some of the timestamp processing.
This need was discovered when we saw some Redix calls were coming in at `0ms`. They are so fast that they were getting rounded down to 0 by `System.convert_time_unit(time, :native, :millisecond)`
=> Increase timestamp resolution

lib/new_relic.ex, lib/new_relic/tracer.ex
Auto `require NewRelic` as a quick convenience so that `other_transaction` can be used wherever `use NewRelic.Tracer` is already used.
=> Auto require NewRelic in NewRelic.Tracer

lib/new_relic/transaction/sidecar.ex, test/sidecar_test.exs
This PR fixes a leak in "Other" transactions that happens when they aren't closed manually.
=> Fix other transaction leak

lib/new_relic/transaction/sidecar.ex, test/other_transaction_test.exs
This PR updates "Other" Transaction behavior so that when it ends with an _expected_ error, it doesn't mark the complete Transaction as having failed.
=> Handle Other transaction ended by expected error

lib/new_relic/distributed_trace.ex, lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex
This PR makes sure we can always encode the sampling priority properly as a float even if an integer gets sent in.
=> Make sure we can always encode priority float

lib/new_relic/instrumented/task.ex
There can be a race condition when the compiler is evaluating these
lines of code, that allow for function_exported? to return false. This
is because the Task module hasn't been loaded yet.
Running `Code.ensure_loaded?(Task)` before calling `function_exported?`
will make sure that we avoid the race condition.
=> Ensure Task is loaded before running function_exported?/3

mix.exs
Hi team.
Thanks for the great software!
This PR simply allows telemetry 1.0 to be used in addition to >= 0.4.
Thanks!
=> Update Telemetry dependency to allow Telemetry 1.0.

README.md
We don't have anyone at NR working on this project in any official way. This badge could be misleading. Please see the Support Statement in the README for the current state of support.
=> Remove community project badge

lib/new_relic/util.ex
=> use `System.pid/0`

lib/new_relic/distributed_trace/new_relic_context.ex, test/distributed_trace_test.exs
**Problem evidence and investigation**
Our NewRelic stopped receiving transactions' metrics collected by the `NewRelic.Telemetry.Plug`. The following log indicated what could be the cause:
```
Handler {:new_relic, :plug} has failed and has been detached.
Class=:error
Reason=:undef
Stacktrace=[
{:invalid, :trust_key, [], []},
{NewRelic.DistributedTrace.NewRelicContext, :restrict_access, 1,
[file: 'lib/new_relic/distributed_trace/new_relic_context.ex', line: 33]},
{NewRelic.DistributedTrace, :newrelic_header, 1,
[file: 'lib/new_relic/distributed_trace.ex', line: 39]},
{NewRelic.DistributedTrace, :accept_distributed_trace_headers, 2,
[file: 'lib/new_relic/distributed_trace.ex', line: 25]},
{NewRelic.DistributedTrace, :determine_context, 2,
[file: 'lib/new_relic/distributed_trace.ex', line: …
```
=> Fix DT payload in unknown version handling

.github/workflows/elixir.yml, README.md, mix.exs, test/collector_protocol_test.exs, test/ssl_test.exs
Elixir 1.9 is the oldest version receiving security patches. Update supported versions to match.
https://hexdocs.pm/elixir/compatibility-and-deprecations.html
=> Support active Elixir versions only

README.md
I was reading the docs looking through how to disable the agent to do some test, but couldn't find it anywhere besides the implementation (https://github.com/newrelic/elixir_agent/blob/master/lib/new_relic/config.ex#L209).
This PR adds this topic to the documentation.
=> docs: add 'Disabling' section to documentation

lib/new_relic/util/http.ex
We're seeing http connection timeouts due to slow server responses. This
allows users to define custom configuration for the httpc request
options so they can pass in a timeout that is relevant for their servers.
Fixes https://github.com/newrelic/elixir_agent/issues/390
=> Allow custom httpc request options to be set

.github/workflows/elixir.yml
Our github actions have been working fine up to September 2022, the last PR to merge.  I think there have been changes with the [setup action](https://github.com/erlef/setup-beam/releases/tag/v1.13.0) and now certain combinations of erlang are throwing errors. 
This [issue comment](https://github.com/erlef/setup-beam/issues/187#issuecomment-1509885275)  shows that the latest ubuntu 22.04 was not built for OTP 23.  
🤔  It makes me wonder how the github action was successful in the past. The logs have expired so can't go back and see what exactly happened with OTP 23, what version of ubuntu was actually used. 
The CI tests are now running.  It is most likely possible to separate out OTP 23 from OTP 24 and have it run on a different ubuntu version. I would need to explore Github actions api …
=> trying something

lib/new_relic.ex, lib/new_relic/harvest/supervisor.ex, lib/new_relic/harvest/telemetry_sdk/api.ex, lib/new_relic/harvest/telemetry_sdk/config.ex, lib/new_relic/harvest/telemetry_sdk/dimensional_metrics/harvester.ex, lib/new_relic/harvest/telemetry_sdk/supervisor.ex, test/dimensional_metric_test.exs, test/integration/integration_test.exs, test/telemetry_sdk/dimensional_metrics_harvester_test.exs
This is a stab to build off of this PR #376 
Looking at the original comments by Vince, I think one missing piece was aggregating the dimensional metrics during the 5 second reporting interval? I took a stab at it.@tpitale , if you have some time, love to hear your thoughts on this. I know @mattbaker  is interested in getting it over the finish line. 
Also, I think that [common block ](https://github.com/newrelic/elixir_agent/commit/95bef6962b1cc9b495ad2e468a28da3cfeaadfb2#diff-acdef3942c8febdf5fe3c3d38c0f8526935fa34e02a0bac66d39560fec274362R84-R85)is accurate for `count` and `summary` - https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api/#optional-map-attributes.
But for `gauge`, it appears the interval.ms value isn't required. It probably does no …
=> Aggregate dimensional metrics

lib/new_relic/config.ex, lib/new_relic/init.ex, lib/new_relic/util/error.ex, test/error_test.exs
We'd like an option to redact arguments in stacktraces before the stacktraces are sent to New Relic.
This draft currently adds a configuration value that will replace arguments in a stacktrace with the string `"DISABLED arity: ($X")`
It's a work in progress.
TODO:
=> Add option to redact args in stacktraces

README.md, config/config.exs, lib/new_relic/error/logger_handler.ex, lib/new_relic/error_logger.ex
This is a follow on to PR https://github.com/newrelic/elixir_agent/pull/421 and should completely address Issue https://github.com/newrelic/elixir_agent/issues/419
The purpose of the new `NewRelic.ErrorLogger` module is to prevent Logger from displaying the MANY status messages caused by enabling `handle_sasl_reports`.
I don't like requiring the user update their `:logger` config to allow the agent to capture errors, but can't think of another way to do it.
This PR also has the nice side effect of not showing the error messages in the console when running `mix test`, because it no longer logs errors to the console during the unit tests.
@tpitale FYI.  This PR plus https://github.com/newrelic/elixir_agent/pull/424, I think it would make a nice update for Elixir users.
=> Additional elixir 1.15 compatibility

README.md
This is a formal request to clarify the experimental status of the Elixir agent. I tried to follow some of the conventions in this template for experimental projects: https://github.com/newrelic/newrelic-experimental-repo-template/tree/main?tab=readme-ov-file
=> Clarify experimental status

lib/new_relic/error/metadata_reporter.ex
This PR fixes a bug within `lib/new_relic/error/metadata_reporter.ex` which can emerge when upgrading from Elixir 1.14 to 1.15 which could manifest as reported errors which were formerly on the Elixir level could report as being wrapped on the Erlang level.
Compare to the use of the `NewRelic.Transaction.Reporter.error` in this PR to here: https://github.com/newrelic/elixir_agent/blob/56525d921f1910430ce84e8e8f0e7d884e67e61a/lib/new_relic/error/reporter.ex#L38  -- can see the `reason` should be an exception struct (which I believe is further parsed as part of the collection cycle), not the "reason" string explanation
```elixir
NewRelic.Transaction.Reporter.error(%{
kind: kind,
reason: exception,
stack: stacktrace
})
```
this reason exception and stacktrace can be extracted directly from …
=> adjust metadata_reporter :transaction report_error

lib/new_relic/telemetry/plug.ex
Sometimes Bandit can't create a conn because of various error states, so we need to handle that condition.
Fixes #447
=> Handle when Bandit was unable to create a conn

lib/new_relic/logger.ex
Using Logger.log makes compile time purge matching [not possible](https://hexdocs.pm/logger/1.9.4/Logger.html#log/3) which means logging is all or nothing with regards to purging.
This change would allow compile time purge matching by log level when using the elixir Logger, so one could get rid of debug logging instead of all logging.
=> Update Logger implementation to be purgeable

.github/workflows/elixir.yml, lib/new_relic/harvest/harvest_cycle.ex
Updates tests to run on most recent 4 Elixir versions, dropping older versions that are no longer receiving Elixir security patches
- https://hexdocs.pm/elixir/1.18.0-rc.0/compatibility-and-deprecations.html
=> Test on latest supported versions

lib/new_relic/config.ex, lib/new_relic/distributed_trace.ex, lib/new_relic/init.ex, lib/new_relic/other_transaction.ex, lib/new_relic/span/reporter.ex, test/distributed_trace_test.exs
This PR wires up Distributed Tracing so that you can disable it via ENV or config if you want, matching other agent behavior.
Closes #401
=> Make Distributed Tracing configurable

lib/new_relic/util.ex, test/transaction_test.exs
We can write binary (but not string) attribute values as "[BINARY_VALUE]" instead of "[BAD_VALUE]", and not log them, since they could occur from builtin instrumentation.
Closes #400
=> Handle binary attribute values better

config/test.exs, lib/new_relic/config.ex, lib/new_relic/init.ex, lib/new_relic/telemetry/plug.ex, lib/new_relic/transaction/reporter.ex, lib/new_relic/transaction/sidecar.ex, lib/new_relic/util.ex, test/transaction_test.exs
This PR enables Web Transactions to be ignored by path using configuration
Common use cases would be ignoring health checks, or ignoring Phoenix `longpoll` requests
Closes #386
=> Support ignoring web transaction paths via configuration

lib/new_relic/config.ex, lib/new_relic/logger.ex
This PR sets the default Agent logging behavior to use the Elixir `Logger`, instead of the current behavior of writing directly to `tmp/new_relic.log`
This could be considered a breaking change. It doesn't change the agent's behavior, but obviously changes where logs go, which is something folks probably care about.
Closes #377
=> Use Elixir Logger as the default agent logger

lib/new_relic/enabled_supervisor.ex, lib/new_relic/os_mon.ex, lib/new_relic/sampler/beam.ex, lib/new_relic/util.ex, mix.exs
We don't need to start `os_mon` when the agent is not enabled (ex: tests), so this starts it only when the agent is enabled, and safely wraps calls into `os_mon` applications.
=> Only start os_mon when agent enabled

lib/new_relic/distributed_trace/backoff_sampler.ex, test/backoff_sampler_test.exs
In #460, we accidentally dropped the line that kicks off the Backoff Sampler cycles. This PR fixes that and adds a test to ensure the cycles are started
=> Fix: Make sure we trigger backoff sampler cycles

lib/new_relic/config.ex, lib/new_relic/init.ex, lib/new_relic/telemetry/ecto/handler.ex, lib/new_relic/tracer/report.ex, test/transaction_test.exs
* Adds "extended" attributes for function tracers (ie: `function.function_name/1.call_count`)
* Makes all "extended" attributes configurable
=> Add extended attrs for functions, make extended attrs configurable

config/test.exs, examples/config/config.exs, lib/new_relic/harvest/collector/protocol.ex, lib/new_relic/telemetry/supervisor.ex, test/evil_collector_test.exs, test/integration/integration_test.exs, test/tracer_test.exs
* We only need to start telemetry handlers when the agent is enabled.  This avoids extra work in the application in situations where the agent is disabled (ex: tests)
* Also adds a config flag to bypass making collector http requests so we can test things w/o trying to actually connect to the collector
=> Only start telemetry handlers when agent is enabled

lib/new_relic/telemetry/phoenix.ex
Don't inspect the `phoenix.view` attribute unless it's present (so we don't send up `"nil"` as the value)
=> Fix: phoenix nil attribute

examples/apps/phx_example/test/phx_example_test.exs, lib/new_relic/telemetry/plug.ex
* bandit attribute `resp_duration_ms` was calculated incorrectly
* bandit `duration` can't be calculated from `monotonic_time` because that is the timestamp of the `exception` event, so use 0 duration when we can't know the actual duration
=> Fix: bandit attributes

examples/apps/oban_example/lib/oban_example/worker.ex, examples/apps/oban_example/test/oban_example_test.exs, examples/apps/redix_example/test/redix_example_test.exs, lib/new_relic.ex, lib/new_relic/telemetry/finch.ex, lib/new_relic/telemetry/oban.ex, lib/new_relic/telemetry/plug.ex, lib/new_relic/tracer/direct.ex, lib/new_relic/tracer/report.ex, lib/new_relic/transaction/complete.ex, lib/new_relic/transaction/reporter.ex, test/span_event_test.exs, test/telemetry/finch_test.exs
This PR contains fixes for a few issues with the `1.31.0` release
* A fix for another instance where the bandit start telemetry doesn't include the `conn` in an error case
* A fix for the `NewRelic.span` macro that was just introduced, but not exercised in tests (oops)
* Wires up Transaction reporting so that we will always have a full set of timing attributes, even if we don't get timing attributes from the instrumentation due to some kind of error. There was a bug revealed when an `Oban` job process exited w/o emitting telemetry, so when we went to "complete" it, it didn't have a needed attribute. This PR fixes this by ensuring the agent automatically put timing attributes on all Transactions. If instrumentation provides more accurate timing attributes, we prefer those over the ones …
=> Fixes: Transaction timing, bandit, span macro

lib/new_relic/transaction/complete.ex, lib/new_relic/transaction/trace.ex, test/transaction_test.exs
There was an assumption in the Transaction Trace processing that relied on the fact that the cowboy web server spawned a process during the transaction. Bandit doesn't have that behavior, which interfered with processing of the segments & how they are nested. This led to segments being duplicated in TTs.
* This PR fixes this situation by making sure the function processing function segments has access the segment representing the root process so it can correctly associate them where they need to go.
* Gets rid of a duplicate layer of nesting at the root of the TT which has always been there but probably shouldn't have been.
* Drops the cowboy specific modification of process spawn count attribute
=> Fix TTs for bandit

examples/apps/ecto_example/test/ecto_example_test.exs, examples/apps/redix_example/test/redix_example_test.exs, lib/new_relic/telemetry/plug.ex, lib/new_relic/transaction/complete.ex, test/metric_transaction_test.exs, test/span_event_test.exs, test/transaction_error_event_test.exs, test/transaction_test.exs
Adds `transaction.name` attribute to the "spans action" span event so it can be correlated to transaction metrics
Closes #490
=> Add transaction.name to spansaction

README.md, lib/new_relic/distributed_trace/new_relic_context.ex, lib/new_relic/harvest/collector/protocol.ex, lib/new_relic/json.ex, lib/new_relic/logs_in_context.ex, lib/new_relic/util/http.ex, lib/new_relic/util/vendor.ex, mix.exs, test/collector_protocol_test.exs, test/custom_event_test.exs, test/distributed_trace_test.exs, test/evil_collector_test.exs, test/infinite_tracing_test.exs, test/logs_in_context_test.exs, test/span_event_test.exs, test/transaction_error_event_test.exs, test/transaction_test.exs, test/transaction_trace_test.exs, test/util_test.exs
Jason has been sunset for later versions of Elixir, and the new JSON library is available as of 1.18.
This could allow less dependencies for apps.
=> Support native JSON library

lib/new_relic/aggregate/aggregate.ex, lib/new_relic/distributed_trace.ex, lib/new_relic/error/trace.ex, lib/new_relic/init.ex, lib/new_relic/sampler/process.ex, lib/new_relic/transaction/complete.ex, lib/new_relic/util.ex, test/transaction_trace_test.exs, test/util_test.exs
There are two cases where Enum functionality is used over Map functionality.
1. Enum.reduce, when the acc is only used for Map.put(acc, ...) -- in this case, Map.new is equivalent, and skips `:lists.foldl` in favor of `Enum.map |> :maps.from_list`, which is faster based on benchmarks by almost 1.5x.
2. Enum.into(enum, %{}) -- in this case, Map.new is equivalent, but is more readable.
```
Mix.install([{:benchee, "~> 1.0"}])
enum = Enum.to_list(1..10000)
Benchee.run(
%{
"map_new" => fn -> Map.new(enum, &{&1, &1}) end,
"enum_into" => fn -> Enum.into(enum, %{}, &{&1, &1}) end,
"enum_reduce" => fn -> Enum.reduce(enum, %{}, &Map.put(&2, &1, &1)) end
},
time: 10,
memory_time: 2
)
```
```
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
reduction …
```
=> Use Map functionality for into and reduce

lib/new_relic/telemetry/plug.ex
This PR fixes a bug that happens sometimes when a bandit request fails early at the socket level. When this happens, bandit can execute telemetry events without the expected `conn` struct. This was partially addressed in https://github.com/newrelic/elixir_agent/pull/483 but there are a few attributes required for a Web Transaction that we need to make sure are always provided.
I was able to reproduce this locally but not consistent enough to write a test for it
```
(Bandit.HTTPError) Header read socket error: :closed
```
=> Fix bug with missing bandit conn

examples/apps/phx_example/lib/phx_example_web/controllers/page_controller.ex, examples/apps/phx_example/test/phx_example_test.exs, lib/new_relic/metric/metric_data.ex, lib/new_relic/telemetry/plug.ex, lib/new_relic/transaction/complete.ex
This PR fixes a display bug reported in https://github.com/newrelic/elixir_agent/issues/489
The bug exists because there were assumptions in the Transaction processing logic that relied on behavior in cowboy that isn't present in bandit, specifically that cowboy would spawn a process to handle the request _after_ the start telemetry was executed, so that process spawn had to be considered when processing total time.
The fix is to only apply that extra processing when the transaction is marked as coming from cowboy.
Also included is a modification to the Transaction breakdown metrics that will give those charts the total time to take into account.
Closes #489
=> Fix incomplete bandit response time metrics

lib/new_relic.ex, lib/new_relic/distributed_trace.ex, lib/new_relic/other_transaction.ex, test/distributed_trace_test.exs
This PR provides support for connecting an Other Transaction to an existing distributed trace. You can provide W3C `traceparent` and `tracestate` headers or another New Relic agent's `newrelic` header.
Closes #265
=> Support connecting an Other Transaction to a Distributed Trace

lib/new_relic/util.ex, test/transaction_test.exs, test/util_test.exs
Improves the way we flatten data structures passed in as attributes.
* Only add the `*.size` attribute when we have dropped some items from Map or List attributes
* Make passing a `Struct` work nicely
=> Improve deep flatten

examples/apps/oban_example/test/oban_example_test.exs, lib/new_relic/telemetry/oban.ex
Oban `queue_time` is reported in `native` units, so we need to convert it to a known unit.
=> Fix Oban queue_time unit

lib/new_relic/logs_in_context.ex, test/logs_in_context_test.exs, test/support/test_helper.ex
This PR extends the Logs in Context feature to handle log messages that are "reports", ie: they don't have a string message, just a keyword list / map. For example:
```elixir
Logger.error(user: 123, error: "something went wrong")
```
=> Handle report messages in logs_in_context

lib/new_relic/logger.ex, test/logger_test.exs
There isn't a pattern matching for the `:warning` atom. It's called by `log/2` which has a guard clause to make sure the level is one of `[:debug, :info, :warning, :error]`, so `:warn` is not a valid option. I also checked who calls `NewRelic.log/2` which delegates to this function, and there isn't occurrences of `:warn`, only `:warning`.
=> Fix elixir_logger/2

lib/new_relic/tracer/direct.ex, lib/new_relic/tracer/macro.ex
This PR increases the resolution of `NewRelic.span` `duration`. Converting directly to `millisecond` can cause very short times to round down to `0`, so we convert to `microsecond` and divide by an extra `1000`
=> Increase resolution of span duration

lib/new_relic/tracer/direct.ex, test/span_event_test.exs
This PR enables using `add_span_attributes` inside a span created with `NewRelic.span` macro
=> Enable adding span attrs inside span macro

examples/apps/phx_example/test/phx_example_test.exs, lib/new_relic/telemetry/plug.ex
Bandit exception telemetry events don't have a `duration`. This fixes our handling of this, instead of inserting `0` as a fallback, we can allow this attribute to be `nil`, and the built in time tracking done by the `Sidecar` will get us an accurate value for duration
=> Fix bandit duration with exception

lib/new_relic/metric/metric_data.ex, lib/new_relic/transaction/complete.ex, lib/new_relic/util/error.ex, test/error_test.exs, test/transaction_error_event_test.exs
This PR makes a small tweak to error "type" classification so that exceptions that arise as an exit get classified as their exception type, not as "exit". This should translate into better grouping in the Errors UI
Also adds Error "blame" metrics that will ensure that per-transaction error metrics are reported.
=> Tweak error classification, metrics

examples/apps/phx_example/test/phx_example_test.exs, lib/new_relic/telemetry/phoenix.ex
This PR adds spans for Phoenix Controller view rendering. Should help identify what work is done inside the rendering of a view.
=> Add spans for phoenix controller view rendering

.gitignore, lib/new_relic/harvest/harvest_cycle.ex, test/telemetry/finch_test.exs
This PR tweaks the harvest shutdown process so that it can handle situations where the harvester has already shut down. This can happen during application shutdown when the agent's manual shutdown process is underway.
Closes #511 
Closes https://github.com/newrelic/elixir_agent/issues/538
Thanks @sgessa for starting this in https://github.com/newrelic/elixir_agent/pull/534
=> Handle shutdown cleaner

lib/new_relic/telemetry/finch.ex, test/telemetry/finch_test.exs
This PR adds a case for parsing the error result from Finch when used with streaming, in which case there's an extra accumulator element in the result tuple.
=> Handle finch streaming error result tuple

lib/new_relic.ex
A small fix for type spec declaration incorrectly referencing `report_custom_event/2` instead of `report_custom_metric/2` (probably a copy-paste error).
=> Fix incorrect spec for report_custom_metric

lib/new_relic/error/reporter/crash_report.ex, lib/new_relic/transaction/complete.ex, lib/new_relic/transaction/reporter.ex, lib/new_relic/transaction/sidecar.ex, test/other_transaction_test.exs
This PR updates Distributed Tracing (specifically "Spansaction") error reporting so that
* Error details show up in the Distributed Tracing UI
* We don't double report errors that are both reported manually in `telemetry` instrumentation and caught by the error logger filter
=> Improve Distributed Tracing error reporting
